---
  - name: Create local working directory
    local_action: file path={{ local_stage_dir }} state=directory mode=0750

  - name: Create remote working directory
    file: path={{ backup_stage_dir }} state=directory mode=0750

  - name: Backup site data
    archive: path="{{ www_dir }}/{{ site_name }}" dest="{{ backup_stage_dir }}/{{ site_name }}.tar.bz2" format=bz2 mode=0640

  - name: Copy site data backup to local storage
    fetch: src={{ backup_stage_dir }}/{{ site_name }}.tar.bz2 dest={{ local_stage_dir }} flat=yes fail_on_missing=yes

