---
- name: Create provider network
  os_network:
    name: "{{ os_neutron_provider_network_name }}"
    external: yes
    provider_network_type: flat
    provider_physical_network: "{{ os_neutron_provider_network_name }}"
    shared: yes
    wait: yes

- name: Create provider subnet
  os_subnet:
    name: "{{ os_neutron_provider_network_name }}-subnet"
    allocation_pool_start: "{{ item.value.start }}"
    allocation_pool_end: "{{ item.value.end }}"
    cidr: "{{ os_network_provider_cidr }}"
    dns_nameservers:
      - 1.1.1.1
      - 8.8.8.8
      - 8.8.4.4
    gateway_ip: "{{ os_network_provider_gw }}"
    enable_dhcp: yes
    network_name: "{{ os_neutron_provider_network_name }}"
    wait: yes
  loop: "{{ os_network_provider_pool|dict2items }}"

- name: Create selfservice network
  os_network:
    name: internal
    shared: yes
    wait: yes

- name: Create selfservice subnet
  os_subnet:
    name: internal-subnet
    cidr: 172.16.1.0/24
    dns_nameservers:
      - 1.1.1.1
      - 8.8.8.8
      - 8.8.4.4
    gateway_ip: 172.16.1.1
    enable_dhcp: yes
    network_name: internal
    wait: yes

- name: Create router for selfservice subnet
  os_router:
    name: internal-router
    interfaces:
      - internal-subnet
    network: "{{ os_neutron_provider_network_name }}"
    wait: yes
