---
  - hosts: openstack
    gather_facts: yes
    become: true
    tasks:

# Dashboard
      - name: Stop apache2
        service:
          name: apache2
          state: stopped

      - name: Uninstall dashboard package
        apt:
          name: openstack-dashboard
          state: absent

      - name: Remove dashboard configuration files
        file:
          path: "{{ item }}"
          state: absent
        with_items:
          - "/etc/openstack-dashboard/"
          - "/etc/apache2/conf-available/openstack-dashboard.conf"
          - "/var/lib/openstack-dashboard/"
          - "/var/lib/apache2/"

# Cinder
      - name: Stop the Block Storage volume service including its dependencies
        service:
          name: "{{ item }}"
          state: stopped
        with_items:
          - tgt
          - cinder-volume
          - cinder-scheduler

      - name: Uninstall cinder packages
        apt:
          name: "{{ item }}"
          state: absent
        with_items:
          - cinder-api
          - cinder-scheduler
          - cinder-volume

      - name: Remove cinder configuration files
        file:
          path: "{{ item }}"
          state: absent
        with_items:
          - "/etc/cinder/"
          - "/var/lib/cinder/"

# Neutron
      - name: Stop neutron services
        service:
          name: "{{ item }}"
          state: stopped
        with_items:
          - neutron-server
          - neutron-linuxbridge-agent
          - neutron-dhcp-agent
          - neutron-metadata-agent
          - neutron-l3-agent

      - name: Uninstall neutron packages
        apt:
          name: "{{ item }}"
          state: absent
        with_items:
          - neutron-server
          - neutron-plugin-ml2
          - neutron-linuxbridge-agent
          - neutron-l3-agent
          - neutron-dhcp-agent
          - neutron-metadata-agent

      - name: Remove neutron configuration files
        file:
          path: "{{ item }}"
          state: absent
        with_items:
          - "/etc/neutron/"
          - "/var/lib/neutron/"

# Nova
      - name: Stop nova services
        service:
          name: "{{ item }}"
          state: stopped
        with_items:
          - nova-compute
          - nova-api
          - nova-consoleauth
          - nova-scheduler
          - nova-conductor
          - nova-novncproxy

      - name: Uninstall nova packages
        apt:
          name: "{{ item }}"
          state: absent
        with_items:
          - nova-compute
          - nova-api
          - nova-conductor
          - nova-consoleauth
          - nova-novncproxy
          - nova-scheduler
          - nova-placement-api

      - name: Remove nova configuration files
        file:
          path: "{{ item }}"
          state: absent
        with_items:
          - "/etc/nova/"
          - "/var/lib/nova/"

# Glance
      - name: Stop glance services
        service:
          name: "{{ item }}"
          state: stopped
        with_items:
          - glance-registry
          - glance-api

      - name: Uninstall glance packages
        apt:
          name: "{{ item }}"
          state: absent
        with_items:
          - glance

      - name: Remove glance configuration files
        file:
          path: "{{ item }}"
          state: absent
        with_items:
          - "/etc/glance/"
          - "/var/lib/glance/"

# Keystone
      - name: Stop keystone services
        service:
          name: "{{ item }}"
          state: stopped
        with_items:
          - apache2

      - name: Uninstall keystone packages
        apt:
          name: "{{ item }}"
          state: absent
        with_items:
          - keystone
          - apache2
          - libapache2-mod-wsgi

      - name: Remove keystone configuration files
        file:
          path: "{{ item }}"
          state: absent
        with_items:
          - "/etc/keystone/"
          - "/etc/apache2/"

# Environment
      - name: Stop openstack related services
        service:
          name: "{{ item }}"
          state: stopped
        with_items:
          - mysql
          - memcached
          - etcd
          - rabbitmq-server

      - name: Uninstall openstack related packages
        apt:
          name: "{{ item }}"
          state: absent
        with_items:
          - memcached
          - python-memcache
          - rabbitmq-server
          - mariadb-server
          - python-pymysql
          - python-mysqldb
          - python-openstackclient

      - name: Remove openstack related configuration files
        file:
          path: "{{ item }}"
          state: absent
        with_items:
          - "/etc/etcd/"
          - "/var/lib/etcd/"
          - "/var/lib/rabbitmq/"
          - "/var/lib/mysql/"
          - "/usr/bin/etcd"
          - "/usr/bin/etcdctl"
          - "/lib/systemd/system/etcd.service"
          - "/etc/mysql/"

      - name: Remove user etcd
        user:
          name: etcd
          state: absent

      - name: Remove group etcd
        group:
          name: etcd
          state: absent
