---
- name: Install the supporting utility packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - lvm2
    - thin-provisioning-tools

- name: Reconfigure LVM to scan only the devices that contain the cinder volume group
  lineinfile:
    path: /etc/lvm/lvm.conf
    # regexp: '^-l 127.0.0.1$'
    insertafter: '(.*)# filter = (.*)'
    line: "        filter = [ \"a/{{ os_cinder_device }}/\", \"r/.*/\"]"
    state: present
  register: lvm_conf_update_status

- name: Install the cinder package
  apt:
    name: cinder-volume
    state: present

- name: Populate cinder config file
  ini_file:
    path: /etc/cinder/cinder.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: "database", option: "connection", value: "mysql+pymysql://cinder:{{ os_cinder_mysql_password }}@controller/cinder" }
    - { section: "DEFAULT", option: "transport_url", value: "rabbit://openstack:{{ os_env_rabbitmq_openstack_password }}@controller" }
    - { section: "DEFAULT", option: "auth_strategy", value: "keystone" }
    - { section: "keystone_authtoken", option: "auth_uri", value: "http://controller:5000" }
    - { section: "keystone_authtoken", option: "auth_url", value: "http://controller:35357" }
    - { section: "keystone_authtoken", option: "memcached_servers", value: "controller:11211" }
    - { section: "keystone_authtoken", option: "auth_type", value: "password" }
    - { section: "keystone_authtoken", option: "project_domain_name", value: "default" }
    - { section: "keystone_authtoken", option: "user_domain_name", value: "default" }
    - { section: "keystone_authtoken", option: "project_name", value: "service" }
    - { section: "keystone_authtoken", option: "username", value: "cinder" }
    - { section: "keystone_authtoken", option: "password", value: "{{ os_cinder_password }}" }
    - { section: "DEFAULT", option: "my_ip", value: "{{ ansible_ssh_host }}" }
    - { section: "lvm", option: "volume_driver", value: "cinder.volume.drivers.lvm.LVMVolumeDriver" }
    - { section: "lvm", option: "volume_group", value: "{{ os_cinder_volume_group }}" }
    - { section: "lvm", option: "iscsi_protocol", value: "iscsi" }
    - { section: "lvm", option: "iscsi_helper", value: "tgtadm" }
    - { section: "DEFAULT", option: "enabled_backends", value: "lvm" }
    - { section: "DEFAULT", option: "glance_api_servers", value: "http://controller:9292" }
    - { section: "oslo_concurrency", option: "lock_path", value: "/var/lib/cinder/tmp" }
  register: cinder_conf_update_status

- name: Restart the Block Storage volume service including its dependencies
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - tgt
    - cinder-volume
  when: lvm_conf_update_status.changed or cinder_conf_update_status.changed