---
  - hosts: openstack
    gather_facts: yes
    become: true
    environment:
      OS_USERNAME: "admin"
      OS_PASSWORD: "{{ os_keystone_admin_password }}"
      OS_PROJECT_NAME: "admin"
      OS_USER_DOMAIN_NAME: "Default"
      OS_PROJECT_DOMAIN_NAME: "Default"
      OS_AUTH_URL: "http://controller:5000/v3"
      OS_IDENTITY_API_VERSION: "3"
    roles:
      - { role: os-install-nova-controller }
