---
- name: Install nova package
  apt:
    name: nova-compute
    state: present

- name: Populate nova.conf config file
  ini_file:
    path: /etc/nova/nova.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: "DEFAULT", option: "transport_url", value: "rabbit://openstack:{{ os_env_rabbitmq_openstack_password }}@controller" }
    - { section: "api", option: "auth_strategy", value: "keystone" }
    - { section: "keystone_authtoken", option: "auth_uri", value: "http://controller:5000" }
    - { section: "keystone_authtoken", option: "auth_url", value: "http://controller:35357" }
    - { section: "keystone_authtoken", option: "memcached_servers", value: "controller:11211" }
    - { section: "keystone_authtoken", option: "auth_type", value: "password" }
    - { section: "keystone_authtoken", option: "project_domain_name", value: "default" }
    - { section: "keystone_authtoken", option: "user_domain_name", value: "default" }
    - { section: "keystone_authtoken", option: "project_name", value: "service" }
    - { section: "keystone_authtoken", option: "username", value: "nova" }
    - { section: "keystone_authtoken", option: "password", value: "{{ os_nova_password }}" }
    - { section: "DEFAULT", option: "my_ip", value: "{{ ansible_ssh_host }}" }
    - { section: "DEFAULT", option: "use_neutron", value: "True" }
    - { section: "DEFAULT", option: "firewall_driver", value: "nova.virt.firewall.NoopFirewallDriver" }
    - { section: "vnc", option: "enabled", value: "true" }
    - { section: "vnc", option: "vncserver_listen", value: "$my_ip" }
    - { section: "vnc", option: "vncserver_proxyclient_address", value: "$my_ip" }
    - { section: "vnc", option: "novncproxy_base_url", value: "http://{{ ansible_ssh_host }}:6080/vnc_auto.html" }
    - { section: "glance", option: "api_servers", value: "http://controller:9292" }
    - { section: "oslo_concurrency", option: "lock_path", value: "/var/lib/nova/tmp" }
    - { section: "placement", option: "os_region_name", value: "RegionOne" }
    - { section: "placement", option: "project_domain_name", value: "Default" }
    - { section: "placement", option: "project_name", value: "service" }
    - { section: "placement", option: "auth_type", value: "password" }
    - { section: "placement", option: "user_domain_name", value: "Default" }
    - { section: "placement", option: "auth_url", value: "http://controller:35357/v3" }
    - { section: "placement", option: "username", value: "placement" }
    - { section: "placement", option: "password", value: "{{ os_placement_password }}" }
  register: nova_compute_conf_file_status

- name: Due to a packaging bug, remove the log_dir option
  ini_file:
    path: /etc/nova/nova.conf
    section: DEFAULT
    option: log_dir
    state: absent

- name: Restart the Compute service
  service:
    name: nova-compute
    state: restarted
  when: nova_compute_conf_file_status.changed
