---
  - name: Create local working directory
    local_action: file path={{ local_stage_dir }} state=directory mode=0750

  - name: Create remote working directory
    file: path={{ backup_stage_dir }} state=directory mode=0750

  - name: Dump database 
    mysql_db: name={{ db_name }} state=dump target={{ backup_stage_dir }}/{{ db_name }}.sql.xz login_user={{ db_user }} login_password={{ db_pass }}

  - name: Copy database dump backup to local storage
    fetch: src={{ backup_stage_dir }}/{{ db_name }}.sql.xz dest={{ local_stage_dir }} flat=yes fail_on_missing=yes

