---
  - name: Create working directory
    local_action: file path={{ local_stage_dir }} state=directory mode=0750

  - name:  Backup nginx configuration
    fetch: src=/etc/nginx/sites-available/{{ site_name }} dest={{ local_stage_dir }} flat=yes fail_on_missing=yes

